name: Testing

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Install dnsdist
      run: |
        sudo apt-get install -y dnsdist net-tools
        sudo systemctl stop dnsdist
    - name: Reconfigure dnsdist to enable the console
      run: |
        sudo cp -rf tests/dnsdist.conf /etc/dnsdist/
        sudo cat /etc/dnsdist/dnsdist.conf
        sudo systemctl start dnsdist
        sudo systemctl status dnsdist
        sudo netstat -anp | grep dnsdist
    - name: Run Python tests
      run: |
        sudo python3 -m pip install libnacl
        sudo python3 -m unittest tests.test_connect